### ISSUE TITLE
Teensy 4.0 compatibility issue

### ISSUE THREAD

**Issue by hhackbarth** [bolderflight/sbus#24]
First let me thank for the good work. On Teensy 3.2 it works like a charm.

But on Teensy 4.0 I can see no output signal. Do you have a chance to test this on Teensy 4?

**Comment by flybrianfly** [comment]
Haven't had a chance to test, but I just pushed a patch that should enable it to work with Teensy 4.

**Comment by hhackbarth** [comment]
Great - Works on T4 now!

**Comment by flybrianfly** [comment]
Awesome! Thanks for the heads up.
