### ISSUE TITLE
 The Sketch uses 76792 bytes (117%) of the program storage space. The maximum is 65536 bytes.

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [bolderflight/sbus#26]
I have a BluePill with 64k of memory and when loading an example Sketch it tells me that there is not enough memory space. Is it right for the library to use so much space? 

How can I make it take up less space?

**Comment by chutsu** [comment]
Can you share what libraries you're using? that sounds like a lot for just 1 library.
Are you using the [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) from stm32duino?

**Comment by FelipeSanchezCalzada** [comment]
For some reason the seller states that the memory is 64k but after several checks I have been able to find out that it is 128k. With 128k the library compiles successfully and loads well.
