### ISSUE TITLE
How to add Compatibility with the Arudino Micro and Arudino Leonardo

### ISSUE THREAD

**Issue by mschindler301** [bolderflight/sbus#31]
I have found a way to add compatibility with the Arduino Micro and Arduino Lenardo (ATMega32u4 based boards). According to the [Arduino Serial Reference](https://www.arduino.cc/en/pmwiki.php?n=Reference/serial), the ATMega32u4 uses Serial1 as its main and only Serial port.

In SBUS.cpp, I added this line to the end of the SBUS::begin()

`_bus->begin(_sbusBaud, SERIAL_8E2); //For ATMega32u4`

And it works! That is the only modification you need to make to the library to make this compatible with ATMega32u4 boards, and I thought this would be a great addition to the library to support more boards.

**Comment by flybrianfly** [comment]
Added.

**Comment by robomaniac** [comment]
was this implemented?  I don't see SBUS::begin() and don't see any ATmega32u4 in the SBUS.cpp file.

I get the classic #include <cstddef> error AVR user have when I select 32u4 board.

it's now SbusRx::Begin()  and uart_->begin

**Comment by robomaniac** [comment]
ah, in #54 you mention older version

> There's some older versions older versions of this library that support AVR; check the checklog. 

do you need command line to check the logs? that is new to me.
I did trial and error and it's 1.0.1 that compile with arduino. I still wish to learn how to check logs.

**Comment by flybrianfly** [comment]
I also maintain a [CHANGELOG](https://github.com/bolderflight/sbus/blob/main/CHANGELOG.md) with notes on major changes between versions. Seems like v2.1.2 might also be an option.

**Comment by robomaniac** [comment]
I appreciated the help
it does compile with 2.1.2 but had to install Embedded_Template_Library (obviously)
preparing hardware to see if I can get it to work. Thanks
