### ISSUE TITLE
STM32 Support

### ISSUE THREAD

**Issue by hjc2** [bolderflight/sbus#32]
Do you think this could work on an adafruit STM32F405 Feather Board? https://www.adafruit.com/product/4382
If there are known issues with this if you could direct me to them so i can decide whether or not it's worth it to switch board or SBUS library for my project that would be great. 
I am aware that i will need some sort of 5v -> 3.3v level converter.
Exact chip on the board: STM32F405 Cortex M4 with FPU and 1MB Flash, 168MHz speed

**Comment by flybrianfly** [comment]
Without taking the time to dig into details of the STM32F405 Arduino core, I can't say for sure whether they could support inverted serial. But they would likely work using a hardware inverter.
