### ISSUE TITLE
SBUS on arduino-STM32L4

### ISSUE THREAD

**Issue by simondlevy** [bolderflight/sbus#4]
Brian,

I've been trying to modify your awesome SBUS library to work with the new line of Arduino-compatible STM32L4 [boards ](https://www.tindie.com/stores/TleraCorp/)from Tlera Corp, using the arduino-STM32L4 [library](https://github.com/GrumpyOldPizza/arduino-STM32L4). Testing with a [FrSky XM SBUS ](https://www.getfpv.com/frsky-xm-receiver.html )receiver, I'm able to see a stream of incoming bytes on RX1, but I can't find a config mask for Serial1.begin() that allows me to see the expected sentinel 0X0F.  I tried every possible combination of masks (inverted/non-inverted, SERIAL_8E1, SERIAL_8E2, even baud rates other than 100K, and still no luck.

If you're interested in taking a shot at this, I'll be happy to send you a couple of the receivers and [Ladybug ](https://www.tindie.com/products/TleraCorp/ladybug-stm32l432-development-board/ ) boards!

Thanks,
Simon

**Comment by flybrianfly** [comment]
Hi Simon,

Interesting. I'll email you my address, it would be interesting to take a look at it.

Best,
Brian
