### ISSUE TITLE
nRF52840 Support like Arduno Nano 33 BLE or Adafruit nRF Feather Express

### ISSUE THREAD

**Issue by marcrupprath** [bolderflight/sbus#40]
Hi, thank you for shaing your lib

It works very well on Teensy 3,1 , but i wan't to  use Arduino Nano 33 BLE, Serial1 for Sbus input
i used with parameters like; "_bus->begin(_sbusBaud, SERIAL_8E2);".  --> Without a result.
But according what was writen about changes for ESP32 , i asking if i need some type of inverter.
It would be even more nice if you can integrate native support for it like for the teensys board.
If not can you explain what i have to change in code , or will it be even more easier to youst use an hardware inverter ?

Thanks in advance

Marc

**Comment by flybrianfly** [comment]
Without taking the time to dig into details of the Arduino Nano 33 core, I can't say for sure whether they could support inverted serial. It's not typically well documented whether inverted serial is supported and how to use. But it would likely work using a hardware inverter. If you want to add native inverted support, you would look for the bus_->begin(...) methods.
