### ISSUE TITLE
Arduino compatible...

### ISSUE THREAD

**Issue by farmaceuta777** [bolderflight/sbus#44]
Hello...
is this library compatible with Arduino boards (328p)? because I can't add the zip file to the Arduino IDE libraries ... it displays an error.

(sorry ... I'm a beginner ..: - /)

**Comment by farmaceuta777** [comment]
Ok thanks for the answer :-)
let me know if it will run on Arduino ..
greetings! :-)

**Comment by flybrianfly** [comment]
I updated the library to include support for the Embedded Template Library for AVR boards. If you follow these instructions, it should work now:
https://github.com/bolderflight/sbus-arduino#installation
