### ISSUE TITLE
SBUS2

### ISSUE THREAD

**Issue by nightfury-11** [bolderflight/sbus#48]
this library is compatible with SBUS2? or just SBUS?

Second, if SBUS2 is not supported, how are you sending data to the transmitter?

**Comment by flybrianfly** [comment]
This library supports receiving actuator commands from a SBUS or SBUS2 receiver and sending commands to SBUS or SBUS2 servos. It does not support the telemetry aspects of SBUS2.

**Comment by nightfury-11** [comment]
does that mean I can record frameloss onto lets say an SD card?

**Comment by flybrianfly** [comment]
Yes, see the lost_frame and failesafe methods in the API.

**Comment by nightfury-11** [comment]
Understood. 

I had a couple questions about the schematic. 

The RX pin will act as the "signal" wire correct? since we are only receiving data and not transmitting it. 

if I'm using an SBUS2 receiver, example R7008SB, should I connect it to the SBUS or SBUS2 port? 

Lastly, since I'll need a serial inverter, can you advise on how I should go about making one?

**Comment by flybrianfly** [comment]
Yes, SBUS signal to the RX pin. I haven't used a Futaba Receiver (just received feedback on making code compatible with them), so you'd have to try both ports and see which would work. I would just search online for inverting circuits, I've only used microcontrollers that support the inverted serial natively.

**Comment by nightfury-11** [comment]
Ok, I'll try both ports. How will I know which one is working and which one isn't? Via the serial monitor?
