### ISSUE TITLE
Seeeduino XIAO trouble

### ISSUE THREAD

**Issue by adrianomazotti** [bolderflight/sbus#52]
I'm not getting it to work on seeeduino XIAO. In the mega 2560 microcontroller it worked correctly, I decided to change the uC and even after many attempts to change the code, it doesn't work correctly

**Comment by flybrianfly** [comment]
Hi, there isn't nearly enough information here for anyone to help you. We would need to understand your hardware setup, your software (especially with code changes), what the expected output is, and what the output that you're seeing it.
