### ISSUE TITLE
Does not compile on arduino uno/nano

### ISSUE THREAD

**Issue by fernsi** [bolderflight/sbus#53]
Arduino: 1.8.18 (Windows Store 1.8.55.0) (Windows 10), Board: "Arduino Uno"

In file included from C:\Users\sebas\OneDrive\Dokumente\Arduino\libraries\Bolder_Flight_Systems_SBUS-7.0.0\examples\arduino\sbus_example\sbus_example.ino:36:0:

C:\Users\sebas\OneDrive\Dokumente\Arduino\libraries\Bolder_Flight_Systems_SBUS-7.0.0\src/sbus.h:34:10: fatal error: cstddef: No such file or directory

 #include <cstddef>

          ^~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by flybrianfly** [comment]
This library is known not to compile on Arduino AVR due to not supporting the STL and the README includes notices of the lack of AVR support. You can use an older version of the library or modify to use something like the Embedded Template Library.
