### ISSUE TITLE
[Question] SBUS to PWM converter

### ISSUE THREAD

**Issue by PaulWieland** [bolderflight/sbus#6]
Would this library be suitable for creating an SBUS to PWM converter to control 5 servos on an airplane?

There doesn't seem to be many options for compact 5 (or 6) channel PWM receivers. The DR4 is the right size but only 4 channels while the 8 channel RX is physically too big for my model.

I'm contemplating using an XSR along with a Trinket (or something similar) to get 5 channels in a smallish footprint.

**Comment by flybrianfly** [comment]
Yes. I've done this quite a lot with the tested boards (Teensy 3.x, Teensy LC, and STM32L4 Ladybug). Keep in mind the board you would like to use would need to have a hardware serial port supporting 8E2 and inverted logic. Also the board would need to have PWM capable pins and PWM library support.
