### ISSUE TITLE
std::array error Seeeduino Xiao Arduino IDE

### ISSUE THREAD

**Issue by swampd32618** [bolderflight/SBUS#76]
Compiling code with std::array I get the following error:

error: 'array' in namespace 'std' does not name a template type

Please adivise as to how to get around this error. Thanks in advance!

**Comment by flybrianfly** [comment]
Please use the latest version downloaded directly from github, which does not use std::array.

**Comment by swampd32618** [comment]
Gotchya - thanks!MarshSent from my iPhoneOn Jan 19, 2024, at 12:50, Brian Taylor ***@***.***> wrote:﻿
Please use the latest version downloaded directly from github, which does not use std::array.
