### ISSUE TITLE
Unable to receive from Futaba R7003SB

### ISSUE THREAD

**Issue by ongbh** [bolderflight/SBUS#79]
Hi Hi,
I tested the library and code with a few devices, including 2 ELRS RX (Happymodel EPW6, Matek R24-P6), flysky FS-iA10B, and a ToolkitRC MC8, however, I just can't get any reading with a Futaba R7003SB.

Any advice on what's best to troubleshooting? I am using a Seed Studio Xiao ESP32.

**Comment by ongbh** [comment]
I managed to capture the Serial output and found this.

F | 0 | sync
1 | 1 |  
1C | 2 |  
20 | 3 |  
A8 | 4 |  
5 | 5 |  
8 | 6 |  
6A | 7 |  
40 | 8 |  
3 | 9 |  
10 | 10 |  
80 | 11 |  
90 | 12 |  
85 | 13 |  
2C | 14 |  
0 | 15 |  
1 | 16 |  
8 | 17 |  
40 | 18 |  
0 | 19 |  
2 | 20 |  
10 | 21 |  
80 | 22 |  
0 | 23 | flag
8 | 24 | footer
0 | 25 |  
3 | 26 |  
C0 | 27 |  
33 | 28 |  
0 | 29 |  

It seems to be a 30 bytes frame instead of 25 bytes frame

When I switch off the Transmitter, the frame become

F | 0 |  Sync
1 | 1 |  
1C | 2 |  
20 | 3 |  
A8 | 4 |  
3 | 5 |  
8 | 6 |  
6A | 7 |  
40 | 8 |  
3 | 9 |  
10 | 10 |  
80 | 11 |  
90 | 12 |  
85 | 13 |  
2C | 14 |  
0 | 15 |  
1 | 16 |  
8 | 17 |  
40 | 18 |  
0 | 19 |  
2 | 20 |  
10 | 21 |  
80 | 22 |  
C | 23 | flag   <- this seems accurate that the bit 4 & 5 is on, meaning fail save and loss of signal is detected.
8 | 24 | footer
0 | 25 |  
3 | 26 |  
4 | 27 |  
0 | 28 |  
0 | 29 |  

Anyone else might be having the same RX to duplicate the problem ?

**Comment by flybrianfly** [comment]
It's probably [this line](https://github.com/bolderflight/sbus/blob/main/src/sbus.cpp#L99) causing an issue. The code is checking that the current byte is the header and the previous byte is the footer. We do that since SBUS only uses a 1 byte header, which could also be found in the payload, so this is a way to give a little more assurance that we're really looking at the header byte.

I thought I had the correct footer for SBUS2 as an option, but I'm not seeing it in your data capture.

**Comment by ongbh** [comment]
I was quite puzzled too, because my "footer" was an consistent 0x08, and my "frame" was a consistent 30bytes instead (including the sync byte). I was wondering if there could be someone else whom can also validate this on a Futaba R7003SB. I am running Fastest-12CH between my Futaba T14SG and the R7003SB.

**Comment by ongbh** [comment]
I going to close this case first. Because when I switch it to FASTest-14CH on my T14SG, the R7003SB can decode okie.
