### ISSUE TITLE
Lost Frame and Failsafe Transmit packet

### ISSUE THREAD

**Issue by flybrianfly** [bolderflight/sbus#8]
Add lost frame and failsafe data to the transmitted packet.

**Comment by Daniel-1276** [comment]
Agree, would be nice to feed also flight controllers with SBUS write function. As already discussed with Brian I am working on a solution to feed analog RSSI data from L9R into SBUS stream for my iNav flight controller.

**Comment by flybrianfly** [comment]
Added support for transmitting lost_frame and failsafe flags.
